# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/ip/FFT_Reorder_x_num_Reorder_fft_0_0/FFT_Reorder_x_num_Reorder_fft_0_0.xci
# IP: The module: 'FFT_Reorder_x_num_Reorder_fft_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/ip/FFT_Reorder_x_num_Reorder_fft_0_0/constraints/Reorder_fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_Reorder_x_num_Reorder_fft_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/ip/FFT_Reorder_x_num_Reorder_fft_0_0/FFT_Reorder_x_num_Reorder_fft_0_0.xci
# IP: The module: 'FFT_Reorder_x_num_Reorder_fft_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/ip/FFT_Reorder_x_num_Reorder_fft_0_0/constraints/Reorder_fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_Reorder_x_num_Reorder_fft_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
