# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/PCIeGen2x4If128.xci
# IP: The module: 'PCIeGen2x4If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/source/PCIeGen2x4If128-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x4If128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/synth/PCIeGen2x4If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x4If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/PCIeGen2x4If128.xci
# IP: The module: 'PCIeGen2x4If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/source/PCIeGen2x4If128-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x4If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/synth/PCIeGen2x4If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x4If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
