// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Reorder_fft,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z045ffg900-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.320000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=18,HLS_SYN_DSP=16,HLS_SYN_FF=4339,HLS_SYN_LUT=4523,HLS_VERSION=2018_3}" *)

module Reorder_fft (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        num_word,
        Real_0_address0,
        Real_0_ce0,
        Real_0_we0,
        Real_0_d0,
        Real_0_q0,
        Real_1_address0,
        Real_1_ce0,
        Real_1_we0,
        Real_1_d0,
        Real_1_q0,
        Real_2_address0,
        Real_2_ce0,
        Real_2_we0,
        Real_2_d0,
        Real_2_q0,
        Real_3_address0,
        Real_3_ce0,
        Real_3_we0,
        Real_3_d0,
        Real_3_q0,
        Imag_0_address0,
        Imag_0_ce0,
        Imag_0_we0,
        Imag_0_d0,
        Imag_0_q0,
        Imag_1_address0,
        Imag_1_ce0,
        Imag_1_we0,
        Imag_1_d0,
        Imag_1_q0,
        Imag_2_address0,
        Imag_2_ce0,
        Imag_2_we0,
        Imag_2_d0,
        Imag_2_q0,
        Imag_3_address0,
        Imag_3_ce0,
        Imag_3_we0,
        Imag_3_d0,
        Imag_3_q0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_pp0_stage0 = 10'd4;
parameter    ap_ST_fsm_pp0_stage1 = 10'd8;
parameter    ap_ST_fsm_state23 = 10'd16;
parameter    ap_ST_fsm_pp1_stage0 = 10'd32;
parameter    ap_ST_fsm_pp1_stage1 = 10'd64;
parameter    ap_ST_fsm_pp1_stage2 = 10'd128;
parameter    ap_ST_fsm_pp1_stage3 = 10'd256;
parameter    ap_ST_fsm_state30 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] num_word;
output  [11:0] Real_0_address0;
output   Real_0_ce0;
output   Real_0_we0;
output  [31:0] Real_0_d0;
input  [31:0] Real_0_q0;
output  [11:0] Real_1_address0;
output   Real_1_ce0;
output   Real_1_we0;
output  [31:0] Real_1_d0;
input  [31:0] Real_1_q0;
output  [11:0] Real_2_address0;
output   Real_2_ce0;
output   Real_2_we0;
output  [31:0] Real_2_d0;
input  [31:0] Real_2_q0;
output  [11:0] Real_3_address0;
output   Real_3_ce0;
output   Real_3_we0;
output  [31:0] Real_3_d0;
input  [31:0] Real_3_q0;
output  [11:0] Imag_0_address0;
output   Imag_0_ce0;
output   Imag_0_we0;
output  [31:0] Imag_0_d0;
input  [31:0] Imag_0_q0;
output  [11:0] Imag_1_address0;
output   Imag_1_ce0;
output   Imag_1_we0;
output  [31:0] Imag_1_d0;
input  [31:0] Imag_1_q0;
output  [11:0] Imag_2_address0;
output   Imag_2_ce0;
output   Imag_2_we0;
output  [31:0] Imag_2_d0;
input  [31:0] Imag_2_q0;
output  [11:0] Imag_3_address0;
output   Imag_3_ce0;
output   Imag_3_we0;
output  [31:0] Imag_3_d0;
input  [31:0] Imag_3_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] Real_0_address0;
reg Real_0_ce0;
reg Real_0_we0;
reg[31:0] Real_0_d0;
reg[11:0] Real_1_address0;
reg Real_1_ce0;
reg Real_1_we0;
reg[31:0] Real_1_d0;
reg[11:0] Real_2_address0;
reg Real_2_ce0;
reg Real_2_we0;
reg[31:0] Real_2_d0;
reg[11:0] Real_3_address0;
reg Real_3_ce0;
reg Real_3_we0;
reg[31:0] Real_3_d0;
reg[11:0] Imag_0_address0;
reg Imag_0_ce0;
reg Imag_0_we0;
reg[31:0] Imag_0_d0;
reg[11:0] Imag_1_address0;
reg Imag_1_ce0;
reg Imag_1_we0;
reg[31:0] Imag_1_d0;
reg[11:0] Imag_2_address0;
reg Imag_2_ce0;
reg Imag_2_we0;
reg[31:0] Imag_2_d0;
reg[11:0] Imag_3_address0;
reg Imag_3_ce0;
reg Imag_3_we0;
reg[31:0] Imag_3_d0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] lut_reorder_I_1024_address0;
reg    lut_reorder_I_1024_ce0;
wire   [9:0] lut_reorder_I_1024_q0;
wire   [8:0] lut_reorder_J_1024_address0;
reg    lut_reorder_J_1024_ce0;
wire   [9:0] lut_reorder_J_1024_q0;
wire   [10:0] lut_reorder_I_4096_address0;
reg    lut_reorder_I_4096_ce0;
wire   [9:0] lut_reorder_I_4096_q0;
wire   [10:0] lut_reorder_J_4096_address0;
reg    lut_reorder_J_4096_ce0;
wire   [11:0] lut_reorder_J_4096_q0;
wire   [12:0] lut_reorder_I_16384_address0;
reg    lut_reorder_I_16384_ce0;
wire   [8:0] lut_reorder_I_16384_q0;
wire   [12:0] lut_reorder_J_16384_address0;
reg    lut_reorder_J_16384_ce0;
wire   [13:0] lut_reorder_J_16384_q0;
reg   [31:0] c_reg_486;
reg   [12:0] i_reg_498;
reg   [29:0] p_lshr_reg_1053;
wire   [0:0] tmp_fu_557_p2;
reg   [0:0] tmp_reg_1058;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_1_fu_562_p2;
reg   [0:0] tmp_1_reg_1065;
wire   [0:0] tmp_4_fu_575_p2;
reg   [0:0] tmp_4_reg_1070;
wire   [11:0] leng_reorder_2_fu_581_p3;
reg   [11:0] leng_reorder_2_reg_1075;
wire   [31:0] tmp_21_fu_640_p3;
reg   [31:0] tmp_21_reg_1080;
wire   [0:0] tmp_22_fu_648_p2;
reg   [0:0] tmp_22_reg_1085;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state9_pp0_stage0_iter3;
wire    ap_block_state11_pp0_stage0_iter4;
wire    ap_block_state13_pp0_stage0_iter5;
wire    ap_block_state15_pp0_stage0_iter6;
wire    ap_block_state17_pp0_stage0_iter7;
wire    ap_block_state19_pp0_stage0_iter8;
wire    ap_block_state21_pp0_stage0_iter9;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_22_reg_1085_pp0_iter1_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter2_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter3_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter4_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter5_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter6_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter7_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter8_reg;
reg   [0:0] tmp_22_reg_1085_pp0_iter9_reg;
wire  signed [29:0] newIndex_fu_653_p4;
reg  signed [29:0] newIndex_reg_1089;
reg  signed [29:0] newIndex_reg_1089_pp0_iter1_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter2_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter3_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter4_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter5_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter6_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter7_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter8_reg;
reg  signed [29:0] newIndex_reg_1089_pp0_iter9_reg;
reg   [11:0] Real_0_addr_reg_1094;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter1_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter2_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter3_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter4_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter5_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter6_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter7_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter8_reg;
reg   [11:0] Real_0_addr_reg_1094_pp0_iter9_reg;
reg   [11:0] Imag_0_addr_reg_1124;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter1_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter2_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter3_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter4_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter5_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter6_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter7_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter8_reg;
reg   [11:0] Imag_0_addr_reg_1124_pp0_iter9_reg;
reg   [31:0] RE_vec_128_a_reg_1134;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state4_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state8_pp0_stage1_iter2;
wire    ap_block_state10_pp0_stage1_iter3;
wire    ap_block_state12_pp0_stage1_iter4;
wire    ap_block_state14_pp0_stage1_iter5;
wire    ap_block_state16_pp0_stage1_iter6;
wire    ap_block_state18_pp0_stage1_iter7;
wire    ap_block_state20_pp0_stage1_iter8;
wire    ap_block_state22_pp0_stage1_iter9;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] RE_vec_128_b_reg_1140;
reg   [31:0] Real_1_load_reg_1145;
reg   [31:0] Imag_1_load_reg_1151;
reg   [31:0] Real_3_load_reg_1157;
reg   [31:0] Imag_3_load_reg_1162;
reg   [31:0] IM_vec_128_a_reg_1167;
reg   [31:0] IM_vec_128_b_reg_1173;
wire   [31:0] tmp_11_1_neg_fu_679_p2;
reg   [31:0] tmp_11_1_neg_reg_1178;
wire   [31:0] tmp_15_1_neg_fu_689_p2;
reg   [31:0] tmp_15_1_neg_reg_1183;
wire   [31:0] tmp_19_1_neg_fu_699_p2;
reg   [31:0] tmp_19_1_neg_reg_1188;
wire   [31:0] tmp_21_1_neg_fu_709_p2;
reg   [31:0] tmp_21_1_neg_reg_1193;
wire   [31:0] c_1_fu_715_p2;
reg   [31:0] c_1_reg_1198;
wire   [31:0] tmp_11_1_fu_721_p1;
wire   [31:0] tmp_15_1_fu_725_p1;
wire   [31:0] tmp_19_1_fu_729_p1;
wire   [31:0] tmp_21_1_fu_733_p1;
wire   [31:0] grp_fu_509_p2;
reg   [31:0] tmp_5_reg_1223;
reg    ap_enable_reg_pp0_iter4;
wire   [31:0] grp_fu_513_p2;
reg   [31:0] tmp_6_reg_1229;
wire   [31:0] grp_fu_517_p2;
reg   [31:0] tmp_9_reg_1235;
wire   [31:0] grp_fu_521_p2;
reg   [31:0] tmp_10_reg_1241;
wire   [31:0] grp_fu_525_p2;
reg   [31:0] tmp_12_1_reg_1247;
wire   [31:0] grp_fu_529_p2;
reg   [31:0] tmp_16_1_reg_1253;
wire   [31:0] grp_fu_533_p2;
reg   [31:0] tmp_20_1_reg_1259;
wire   [31:0] grp_fu_537_p2;
reg   [31:0] tmp_22_1_reg_1265;
wire   [31:0] tmp_23_1_neg_fu_740_p2;
reg   [31:0] tmp_23_1_neg_reg_1271;
wire   [31:0] tmp_17_2_neg_fu_749_p2;
reg   [31:0] tmp_17_2_neg_reg_1276;
wire   [31:0] tmp_23_2_neg_fu_758_p2;
reg   [31:0] tmp_23_2_neg_reg_1281;
wire   [31:0] tmp_17_3_neg_fu_767_p2;
reg   [31:0] tmp_17_3_neg_reg_1286;
wire   [31:0] tmp_23_1_fu_773_p1;
wire   [31:0] tmp_17_2_fu_777_p1;
wire   [31:0] tmp_23_2_fu_781_p1;
wire   [31:0] tmp_17_3_fu_785_p1;
reg   [31:0] tmp_7_reg_1311;
reg    ap_enable_reg_pp0_iter9;
reg   [31:0] tmp_11_reg_1316;
reg   [31:0] tmp_18_1_reg_1321;
reg   [31:0] tmp_24_1_reg_1326;
reg   [31:0] tmp_18_2_reg_1331;
reg   [31:0] tmp_24_2_reg_1336;
reg   [31:0] tmp_18_3_reg_1341;
reg   [31:0] tmp_24_3_reg_1346;
wire  signed [12:0] tmp_14_fu_807_p1;
reg  signed [12:0] tmp_14_reg_1363;
wire    ap_CS_fsm_state23;
wire   [0:0] sel_tmp2_fu_815_p2;
reg   [0:0] sel_tmp2_reg_1368;
wire   [0:0] sel_tmp7_fu_825_p2;
reg   [0:0] sel_tmp7_reg_1374;
wire   [0:0] exitcond_fu_831_p2;
reg   [0:0] exitcond_reg_1380;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state24_pp1_stage0_iter0;
wire    ap_block_state28_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [12:0] i_1_fu_836_p2;
reg   [12:0] i_1_reg_1384;
reg    ap_enable_reg_pp1_iter0;
reg   [9:0] indexI_1_reg_1419;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_state25_pp1_stage1_iter0;
wire    ap_block_state29_pp1_stage1_iter1;
wire    ap_block_pp1_stage1_11001;
reg   [9:0] indexI_2_reg_1424;
reg   [8:0] indexI_4_reg_1429;
wire   [1:0] tmp_24_fu_888_p1;
reg   [1:0] tmp_24_reg_1434;
reg   [29:0] newIndex5_reg_1439;
reg   [11:0] Real_0_addr_2_reg_1444;
wire    ap_CS_fsm_pp1_stage2;
wire    ap_block_state26_pp1_stage2_iter0;
wire    ap_block_pp1_stage2_11001;
reg   [11:0] Real_1_addr_2_reg_1449;
reg   [11:0] Real_2_addr_2_reg_1454;
reg   [11:0] Real_3_addr_2_reg_1459;
reg   [11:0] Imag_0_addr_2_reg_1464;
reg   [11:0] Imag_1_addr_2_reg_1469;
reg   [11:0] Imag_2_addr_2_reg_1474;
reg   [11:0] Imag_3_addr_2_reg_1479;
wire   [1:0] tmp_23_fu_951_p1;
reg   [1:0] tmp_23_reg_1484;
wire    ap_CS_fsm_pp1_stage3;
wire    ap_block_state27_pp1_stage3_iter0;
wire    ap_block_pp1_stage3_11001;
reg   [11:0] Real_0_addr_1_reg_1489;
reg   [11:0] Real_1_addr_1_reg_1494;
reg   [11:0] Real_2_addr_1_reg_1499;
reg   [11:0] Real_3_addr_1_reg_1504;
reg   [11:0] Imag_0_addr_1_reg_1509;
reg   [11:0] Imag_1_addr_1_reg_1514;
reg   [11:0] Imag_2_addr_1_reg_1519;
reg   [11:0] Imag_3_addr_1_reg_1524;
wire   [31:0] tmp_16_fu_980_p6;
reg   [31:0] tmp_16_reg_1529;
wire   [31:0] tmp_17_fu_999_p6;
reg   [31:0] tmp_17_reg_1537;
wire   [31:0] tempr_fu_1016_p6;
reg   [31:0] tempr_reg_1545;
wire   [31:0] tempi_fu_1030_p6;
reg   [31:0] tempi_reg_1553;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state24;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage3_subdone;
wire    ap_block_pp1_stage1_subdone;
reg   [31:0] ap_phi_mux_c_phi_fu_490_p4;
wire    ap_block_pp0_stage0;
reg   [12:0] ap_phi_mux_i_phi_fu_502_p4;
wire    ap_block_pp1_stage0;
wire   [63:0] newIndex1_fu_663_p1;
wire   [63:0] newIndex2_fu_792_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_s_fu_842_p1;
wire   [63:0] newIndex6_fu_907_p1;
wire    ap_block_pp1_stage2;
wire   [63:0] newIndex4_fu_965_p1;
wire    ap_block_pp1_stage3;
reg   [31:0] indexJ_fu_114;
wire   [31:0] indexJ_3_fu_881_p3;
wire    ap_block_pp1_stage1;
reg   [31:0] indexI_fu_118;
wire   [31:0] indexI_3_fu_944_p3;
reg   [31:0] grp_fu_509_p0;
reg   [31:0] grp_fu_509_p1;
reg   [31:0] grp_fu_513_p0;
reg   [31:0] grp_fu_513_p1;
reg   [31:0] grp_fu_517_p0;
reg   [31:0] grp_fu_517_p1;
reg   [31:0] grp_fu_521_p0;
reg   [31:0] grp_fu_521_p1;
reg   [31:0] grp_fu_525_p0;
reg   [31:0] grp_fu_525_p1;
reg   [31:0] grp_fu_529_p0;
reg   [31:0] grp_fu_529_p1;
reg   [31:0] grp_fu_533_p0;
reg   [31:0] grp_fu_533_p1;
reg   [31:0] grp_fu_537_p0;
reg   [31:0] grp_fu_537_p1;
wire   [31:0] p_neg_fu_541_p2;
wire   [11:0] p_cast_fu_567_p3;
wire   [31:0] num_word_op_op_fu_596_p2;
wire   [0:0] tmp_12_fu_601_p3;
wire   [29:0] p_neg_t_fu_609_p2;
wire   [29:0] tmp_18_fu_614_p4;
wire   [0:0] tmp_2_fu_589_p3;
wire   [29:0] tmp_19_fu_624_p3;
wire   [29:0] tmp_20_fu_632_p3;
wire   [31:0] tmp_11_1_to_int_fu_675_p1;
wire   [31:0] tmp_15_1_to_int_fu_685_p1;
wire   [31:0] tmp_19_1_to_int_fu_695_p1;
wire   [31:0] tmp_21_1_to_int_fu_705_p1;
wire   [31:0] tmp_23_1_to_int_fu_737_p1;
wire   [31:0] tmp_17_2_to_int_fu_746_p1;
wire   [31:0] tmp_23_2_to_int_fu_755_p1;
wire   [31:0] tmp_17_3_to_int_fu_764_p1;
wire  signed [61:0] tmp_13_fu_789_p1;
wire   [0:0] sel_tmp1_fu_810_p2;
wire   [0:0] tmp_8_fu_802_p2;
wire   [0:0] sel_tmp6_fu_820_p2;
wire   [31:0] indexJ_1_cast_fu_855_p1;
wire   [31:0] indexJ_2_cast_fu_859_p1;
wire   [31:0] indexJ_5_fu_867_p3;
wire   [31:0] indexJ_4_cast_fu_863_p1;
wire   [31:0] indexJ_6_fu_874_p3;
wire   [31:0] indexI_1_cast_fu_921_p1;
wire   [31:0] indexI_2_cast_fu_924_p1;
wire   [31:0] indexI_5_fu_930_p3;
wire   [31:0] indexI_4_cast_fu_927_p1;
wire   [31:0] indexI_6_fu_937_p3;
wire   [29:0] newIndex3_fu_955_p4;
wire   [31:0] arrayNo1_fu_977_p1;
wire   [31:0] arrayNo_fu_1013_p1;
wire    ap_CS_fsm_state30;
reg   [9:0] ap_NS_fsm;
wire    ap_block_pp1_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
end

Reorder_fft_lut_rbkb #(
    .DataWidth( 10 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
lut_reorder_I_1024_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_reorder_I_1024_address0),
    .ce0(lut_reorder_I_1024_ce0),
    .q0(lut_reorder_I_1024_q0)
);

Reorder_fft_lut_rcud #(
    .DataWidth( 10 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
lut_reorder_J_1024_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_reorder_J_1024_address0),
    .ce0(lut_reorder_J_1024_ce0),
    .q0(lut_reorder_J_1024_q0)
);

Reorder_fft_lut_rdEe #(
    .DataWidth( 10 ),
    .AddressRange( 2016 ),
    .AddressWidth( 11 ))
lut_reorder_I_4096_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_reorder_I_4096_address0),
    .ce0(lut_reorder_I_4096_ce0),
    .q0(lut_reorder_I_4096_q0)
);

Reorder_fft_lut_reOg #(
    .DataWidth( 12 ),
    .AddressRange( 2016 ),
    .AddressWidth( 11 ))
lut_reorder_J_4096_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_reorder_J_4096_address0),
    .ce0(lut_reorder_J_4096_ce0),
    .q0(lut_reorder_J_4096_q0)
);

Reorder_fft_lut_rfYi #(
    .DataWidth( 9 ),
    .AddressRange( 8064 ),
    .AddressWidth( 13 ))
lut_reorder_I_16384_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_reorder_I_16384_address0),
    .ce0(lut_reorder_I_16384_ce0),
    .q0(lut_reorder_I_16384_q0)
);

Reorder_fft_lut_rg8j #(
    .DataWidth( 14 ),
    .AddressRange( 8064 ),
    .AddressWidth( 13 ))
lut_reorder_J_16384_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_reorder_J_16384_address0),
    .ce0(lut_reorder_J_16384_ce0),
    .q0(lut_reorder_J_16384_q0)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_509_p0),
    .din1(grp_fu_509_p1),
    .ce(1'b1),
    .dout(grp_fu_509_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_513_p0),
    .din1(grp_fu_513_p1),
    .ce(1'b1),
    .dout(grp_fu_513_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_517_p0),
    .din1(grp_fu_517_p1),
    .ce(1'b1),
    .dout(grp_fu_517_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_521_p0),
    .din1(grp_fu_521_p1),
    .ce(1'b1),
    .dout(grp_fu_521_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_525_p0),
    .din1(grp_fu_525_p1),
    .ce(1'b1),
    .dout(grp_fu_525_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_529_p0),
    .din1(grp_fu_529_p1),
    .ce(1'b1),
    .dout(grp_fu_529_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_533_p0),
    .din1(grp_fu_533_p1),
    .ce(1'b1),
    .dout(grp_fu_533_p2)
);

Reorder_fft_fadd_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_fadd_hbi_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_537_p0),
    .din1(grp_fu_537_p1),
    .ce(1'b1),
    .dout(grp_fu_537_p2)
);

Reorder_fft_mux_4ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_mux_4ibs_U9(
    .din0(Real_0_q0),
    .din1(Real_1_q0),
    .din2(Real_2_q0),
    .din3(Real_3_q0),
    .din4(arrayNo1_fu_977_p1),
    .dout(tmp_16_fu_980_p6)
);

Reorder_fft_mux_4ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_mux_4ibs_U10(
    .din0(Imag_0_q0),
    .din1(Imag_1_q0),
    .din2(Imag_2_q0),
    .din3(Imag_3_q0),
    .din4(arrayNo1_fu_977_p1),
    .dout(tmp_17_fu_999_p6)
);

Reorder_fft_mux_4ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_mux_4ibs_U11(
    .din0(Real_0_q0),
    .din1(Real_1_q0),
    .din2(Real_2_q0),
    .din3(Real_3_q0),
    .din4(arrayNo_fu_1013_p1),
    .dout(tempr_fu_1016_p6)
);

Reorder_fft_mux_4ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Reorder_fft_mux_4ibs_U12(
    .din0(Imag_0_q0),
    .din1(Imag_1_q0),
    .din2(Imag_2_q0),
    .din3(Imag_3_q0),
    .din4(arrayNo_fu_1013_p1),
    .dout(tempi_fu_1030_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state24) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp1_stage3_subdone) & (1'b1 == ap_CS_fsm_pp1_stage3)) | ((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1)))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_22_reg_1085 == 1'd0))) begin
        c_reg_486 <= c_1_reg_1198;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_reg_486 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        i_reg_498 <= 13'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_reg_1380 == 1'd0))) begin
        i_reg_498 <= i_1_reg_1384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085 == 1'd0))) begin
        IM_vec_128_a_reg_1167 <= Imag_0_q0;
        IM_vec_128_b_reg_1173 <= Imag_2_q0;
        Imag_1_load_reg_1151 <= Imag_1_q0;
        Imag_3_load_reg_1162 <= Imag_3_q0;
        RE_vec_128_a_reg_1134 <= Real_0_q0;
        RE_vec_128_b_reg_1140 <= Real_2_q0;
        Real_1_load_reg_1145 <= Real_1_q0;
        Real_3_load_reg_1157 <= Real_3_q0;
        c_1_reg_1198 <= c_1_fu_715_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (exitcond_reg_1380 == 1'd0))) begin
        Imag_0_addr_1_reg_1509 <= newIndex4_fu_965_p1;
        Imag_1_addr_1_reg_1514 <= newIndex4_fu_965_p1;
        Imag_2_addr_1_reg_1519 <= newIndex4_fu_965_p1;
        Imag_3_addr_1_reg_1524 <= newIndex4_fu_965_p1;
        Real_0_addr_1_reg_1489 <= newIndex4_fu_965_p1;
        Real_1_addr_1_reg_1494 <= newIndex4_fu_965_p1;
        Real_2_addr_1_reg_1499 <= newIndex4_fu_965_p1;
        Real_3_addr_1_reg_1504 <= newIndex4_fu_965_p1;
        tmp_16_reg_1529 <= tmp_16_fu_980_p6;
        tmp_17_reg_1537 <= tmp_17_fu_999_p6;
        tmp_23_reg_1484 <= tmp_23_fu_951_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (exitcond_reg_1380 == 1'd0))) begin
        Imag_0_addr_2_reg_1464 <= newIndex6_fu_907_p1;
        Imag_1_addr_2_reg_1469 <= newIndex6_fu_907_p1;
        Imag_2_addr_2_reg_1474 <= newIndex6_fu_907_p1;
        Imag_3_addr_2_reg_1479 <= newIndex6_fu_907_p1;
        Real_0_addr_2_reg_1444 <= newIndex6_fu_907_p1;
        Real_1_addr_2_reg_1449 <= newIndex6_fu_907_p1;
        Real_2_addr_2_reg_1454 <= newIndex6_fu_907_p1;
        Real_3_addr_2_reg_1459 <= newIndex6_fu_907_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_22_fu_648_p2 == 1'd0))) begin
        Imag_0_addr_reg_1124 <= newIndex1_fu_663_p1;
        Real_0_addr_reg_1094 <= newIndex1_fu_663_p1;
        newIndex_reg_1089 <= {{ap_phi_mux_c_phi_fu_490_p4[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Imag_0_addr_reg_1124_pp0_iter1_reg <= Imag_0_addr_reg_1124;
        Imag_0_addr_reg_1124_pp0_iter2_reg <= Imag_0_addr_reg_1124_pp0_iter1_reg;
        Imag_0_addr_reg_1124_pp0_iter3_reg <= Imag_0_addr_reg_1124_pp0_iter2_reg;
        Imag_0_addr_reg_1124_pp0_iter4_reg <= Imag_0_addr_reg_1124_pp0_iter3_reg;
        Imag_0_addr_reg_1124_pp0_iter5_reg <= Imag_0_addr_reg_1124_pp0_iter4_reg;
        Imag_0_addr_reg_1124_pp0_iter6_reg <= Imag_0_addr_reg_1124_pp0_iter5_reg;
        Imag_0_addr_reg_1124_pp0_iter7_reg <= Imag_0_addr_reg_1124_pp0_iter6_reg;
        Imag_0_addr_reg_1124_pp0_iter8_reg <= Imag_0_addr_reg_1124_pp0_iter7_reg;
        Imag_0_addr_reg_1124_pp0_iter9_reg <= Imag_0_addr_reg_1124_pp0_iter8_reg;
        Real_0_addr_reg_1094_pp0_iter1_reg <= Real_0_addr_reg_1094;
        Real_0_addr_reg_1094_pp0_iter2_reg <= Real_0_addr_reg_1094_pp0_iter1_reg;
        Real_0_addr_reg_1094_pp0_iter3_reg <= Real_0_addr_reg_1094_pp0_iter2_reg;
        Real_0_addr_reg_1094_pp0_iter4_reg <= Real_0_addr_reg_1094_pp0_iter3_reg;
        Real_0_addr_reg_1094_pp0_iter5_reg <= Real_0_addr_reg_1094_pp0_iter4_reg;
        Real_0_addr_reg_1094_pp0_iter6_reg <= Real_0_addr_reg_1094_pp0_iter5_reg;
        Real_0_addr_reg_1094_pp0_iter7_reg <= Real_0_addr_reg_1094_pp0_iter6_reg;
        Real_0_addr_reg_1094_pp0_iter8_reg <= Real_0_addr_reg_1094_pp0_iter7_reg;
        Real_0_addr_reg_1094_pp0_iter9_reg <= Real_0_addr_reg_1094_pp0_iter8_reg;
        newIndex_reg_1089_pp0_iter1_reg <= newIndex_reg_1089;
        newIndex_reg_1089_pp0_iter2_reg <= newIndex_reg_1089_pp0_iter1_reg;
        newIndex_reg_1089_pp0_iter3_reg <= newIndex_reg_1089_pp0_iter2_reg;
        newIndex_reg_1089_pp0_iter4_reg <= newIndex_reg_1089_pp0_iter3_reg;
        newIndex_reg_1089_pp0_iter5_reg <= newIndex_reg_1089_pp0_iter4_reg;
        newIndex_reg_1089_pp0_iter6_reg <= newIndex_reg_1089_pp0_iter5_reg;
        newIndex_reg_1089_pp0_iter7_reg <= newIndex_reg_1089_pp0_iter6_reg;
        newIndex_reg_1089_pp0_iter8_reg <= newIndex_reg_1089_pp0_iter7_reg;
        newIndex_reg_1089_pp0_iter9_reg <= newIndex_reg_1089_pp0_iter8_reg;
        tmp_22_reg_1085 <= tmp_22_fu_648_p2;
        tmp_22_reg_1085_pp0_iter1_reg <= tmp_22_reg_1085;
        tmp_22_reg_1085_pp0_iter2_reg <= tmp_22_reg_1085_pp0_iter1_reg;
        tmp_22_reg_1085_pp0_iter3_reg <= tmp_22_reg_1085_pp0_iter2_reg;
        tmp_22_reg_1085_pp0_iter4_reg <= tmp_22_reg_1085_pp0_iter3_reg;
        tmp_22_reg_1085_pp0_iter5_reg <= tmp_22_reg_1085_pp0_iter4_reg;
        tmp_22_reg_1085_pp0_iter6_reg <= tmp_22_reg_1085_pp0_iter5_reg;
        tmp_22_reg_1085_pp0_iter7_reg <= tmp_22_reg_1085_pp0_iter6_reg;
        tmp_22_reg_1085_pp0_iter8_reg <= tmp_22_reg_1085_pp0_iter7_reg;
        tmp_22_reg_1085_pp0_iter9_reg <= tmp_22_reg_1085_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        exitcond_reg_1380 <= exitcond_fu_831_p2;
        tempi_reg_1553 <= tempi_fu_1030_p6;
        tempr_reg_1545 <= tempr_fu_1016_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_1_reg_1384 <= i_1_fu_836_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (exitcond_reg_1380 == 1'd0) & (sel_tmp7_reg_1374 == 1'd0) & (sel_tmp2_reg_1368 == 1'd0) & (tmp_reg_1058 == 1'd1))) begin
        indexI_1_reg_1419 <= lut_reorder_I_1024_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (sel_tmp2_reg_1368 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (exitcond_reg_1380 == 1'd0) & (sel_tmp7_reg_1374 == 1'd0))) begin
        indexI_2_reg_1424 <= lut_reorder_I_4096_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (sel_tmp7_reg_1374 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (exitcond_reg_1380 == 1'd0))) begin
        indexI_4_reg_1429 <= lut_reorder_I_16384_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1) & (exitcond_reg_1380 == 1'd0))) begin
        indexI_fu_118 <= indexI_3_fu_944_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (exitcond_reg_1380 == 1'd0))) begin
        indexJ_fu_114 <= indexJ_3_fu_881_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        leng_reorder_2_reg_1075[6 : 5] <= leng_reorder_2_fu_581_p3[6 : 5];
leng_reorder_2_reg_1075[11 : 9] <= leng_reorder_2_fu_581_p3[11 : 9];
        tmp_1_reg_1065 <= tmp_1_fu_562_p2;
        tmp_21_reg_1080[31 : 2] <= tmp_21_fu_640_p3[31 : 2];
        tmp_4_reg_1070 <= tmp_4_fu_575_p2;
        tmp_reg_1058 <= tmp_fu_557_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (exitcond_reg_1380 == 1'd0))) begin
        newIndex5_reg_1439 <= {{indexJ_3_fu_881_p3[31:2]}};
        tmp_24_reg_1434 <= tmp_24_fu_888_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_lshr_reg_1053 <= {{p_neg_fu_541_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        sel_tmp2_reg_1368 <= sel_tmp2_fu_815_p2;
        sel_tmp7_reg_1374 <= sel_tmp7_fu_825_p2;
        tmp_14_reg_1363[6 : 5] <= tmp_14_fu_807_p1[6 : 5];
tmp_14_reg_1363[12 : 9] <= tmp_14_fu_807_p1[12 : 9];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter4_reg == 1'd0))) begin
        tmp_10_reg_1241 <= grp_fu_521_p2;
        tmp_12_1_reg_1247 <= grp_fu_525_p2;
        tmp_16_1_reg_1253 <= grp_fu_529_p2;
        tmp_20_1_reg_1259 <= grp_fu_533_p2;
        tmp_22_1_reg_1265 <= grp_fu_537_p2;
        tmp_5_reg_1223 <= grp_fu_509_p2;
        tmp_6_reg_1229 <= grp_fu_513_p2;
        tmp_9_reg_1235 <= grp_fu_517_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085 == 1'd0))) begin
        tmp_11_1_neg_reg_1178 <= tmp_11_1_neg_fu_679_p2;
        tmp_15_1_neg_reg_1183 <= tmp_15_1_neg_fu_689_p2;
        tmp_19_1_neg_reg_1188 <= tmp_19_1_neg_fu_699_p2;
        tmp_21_1_neg_reg_1193 <= tmp_21_1_neg_fu_709_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_reg_1085_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_11_reg_1316 <= grp_fu_513_p2;
        tmp_18_1_reg_1321 <= grp_fu_517_p2;
        tmp_18_2_reg_1331 <= grp_fu_525_p2;
        tmp_18_3_reg_1341 <= grp_fu_533_p2;
        tmp_24_1_reg_1326 <= grp_fu_521_p2;
        tmp_24_2_reg_1336 <= grp_fu_529_p2;
        tmp_24_3_reg_1346 <= grp_fu_537_p2;
        tmp_7_reg_1311 <= grp_fu_509_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_reg_1085_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_17_2_neg_reg_1276 <= tmp_17_2_neg_fu_749_p2;
        tmp_17_3_neg_reg_1286 <= tmp_17_3_neg_fu_767_p2;
        tmp_23_1_neg_reg_1271 <= tmp_23_1_neg_fu_740_p2;
        tmp_23_2_neg_reg_1281 <= tmp_23_2_neg_fu_758_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_0_address0 = Imag_0_addr_2_reg_1464;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_0_address0 = Imag_0_addr_1_reg_1509;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_0_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_0_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_0_address0 = Imag_0_addr_reg_1124_pp0_iter9_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Imag_0_address0 = newIndex1_fu_663_p1;
    end else begin
        Imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Imag_0_ce0 = 1'b1;
    end else begin
        Imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_0_d0 = tempi_reg_1553;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_0_d0 = tmp_17_reg_1537;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_0_d0 = tmp_11_reg_1316;
    end else begin
        Imag_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Imag_0_we0 = 1'b1;
    end else begin
        Imag_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_1_address0 = Imag_1_addr_2_reg_1469;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_1_address0 = Imag_1_addr_1_reg_1514;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_1_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_1_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_1_address0 = newIndex2_fu_792_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Imag_1_address0 = newIndex1_fu_663_p1;
    end else begin
        Imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Imag_1_ce0 = 1'b1;
    end else begin
        Imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_1_d0 = tempi_reg_1553;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_1_d0 = tmp_17_reg_1537;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_1_d0 = tmp_24_1_reg_1326;
    end else begin
        Imag_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd1) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Imag_1_we0 = 1'b1;
    end else begin
        Imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_2_address0 = Imag_2_addr_2_reg_1474;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_2_address0 = Imag_2_addr_1_reg_1519;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_2_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_2_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_2_address0 = newIndex2_fu_792_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Imag_2_address0 = newIndex1_fu_663_p1;
    end else begin
        Imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Imag_2_ce0 = 1'b1;
    end else begin
        Imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_2_d0 = tempi_reg_1553;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_2_d0 = tmp_17_reg_1537;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_2_d0 = tmp_24_2_reg_1336;
    end else begin
        Imag_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd2) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd2) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Imag_2_we0 = 1'b1;
    end else begin
        Imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_3_address0 = Imag_3_addr_2_reg_1479;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_3_address0 = Imag_3_addr_1_reg_1524;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_3_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Imag_3_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_3_address0 = newIndex2_fu_792_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Imag_3_address0 = newIndex1_fu_663_p1;
    end else begin
        Imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Imag_3_ce0 = 1'b1;
    end else begin
        Imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Imag_3_d0 = tempi_reg_1553;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Imag_3_d0 = tmp_17_reg_1537;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Imag_3_d0 = tmp_24_3_reg_1346;
    end else begin
        Imag_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd3) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd3) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Imag_3_we0 = 1'b1;
    end else begin
        Imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_0_address0 = Real_0_addr_2_reg_1444;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_0_address0 = Real_0_addr_1_reg_1489;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_0_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_0_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_0_address0 = Real_0_addr_reg_1094_pp0_iter9_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Real_0_address0 = newIndex1_fu_663_p1;
    end else begin
        Real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Real_0_ce0 = 1'b1;
    end else begin
        Real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_0_d0 = tempr_reg_1545;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_0_d0 = tmp_16_reg_1529;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_0_d0 = tmp_7_reg_1311;
    end else begin
        Real_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Real_0_we0 = 1'b1;
    end else begin
        Real_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_1_address0 = Real_1_addr_2_reg_1449;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_1_address0 = Real_1_addr_1_reg_1494;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_1_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_1_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_1_address0 = newIndex2_fu_792_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Real_1_address0 = newIndex1_fu_663_p1;
    end else begin
        Real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Real_1_ce0 = 1'b1;
    end else begin
        Real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_1_d0 = tempr_reg_1545;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_1_d0 = tmp_16_reg_1529;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_1_d0 = tmp_18_1_reg_1321;
    end else begin
        Real_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd1) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Real_1_we0 = 1'b1;
    end else begin
        Real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_2_address0 = Real_2_addr_2_reg_1454;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_2_address0 = Real_2_addr_1_reg_1499;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_2_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_2_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_2_address0 = newIndex2_fu_792_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Real_2_address0 = newIndex1_fu_663_p1;
    end else begin
        Real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Real_2_ce0 = 1'b1;
    end else begin
        Real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_2_d0 = tempr_reg_1545;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_2_d0 = tmp_16_reg_1529;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_2_d0 = tmp_18_2_reg_1331;
    end else begin
        Real_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd2) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd2) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Real_2_we0 = 1'b1;
    end else begin
        Real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_3_address0 = Real_3_addr_2_reg_1459;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_3_address0 = Real_3_addr_1_reg_1504;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_3_address0 = newIndex4_fu_965_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        Real_3_address0 = newIndex6_fu_907_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_3_address0 = newIndex2_fu_792_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Real_3_address0 = newIndex1_fu_663_p1;
    end else begin
        Real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        Real_3_ce0 = 1'b1;
    end else begin
        Real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        Real_3_d0 = tempr_reg_1545;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        Real_3_d0 = tmp_16_reg_1529;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Real_3_d0 = tmp_18_3_reg_1341;
    end else begin
        Real_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_24_reg_1434 == 2'd3) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((tmp_23_reg_1484 == 2'd3) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_22_reg_1085_pp0_iter9_reg == 1'd0)))) begin
        Real_3_we0 = 1'b1;
    end else begin
        Real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_22_fu_648_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_fu_831_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state24 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state24 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_reg_1085 == 1'd0))) begin
        ap_phi_mux_c_phi_fu_490_p4 = c_1_reg_1198;
    end else begin
        ap_phi_mux_c_phi_fu_490_p4 = c_reg_486;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_reg_1380 == 1'd0))) begin
        ap_phi_mux_i_phi_fu_502_p4 = i_1_reg_1384;
    end else begin
        ap_phi_mux_i_phi_fu_502_p4 = i_reg_498;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_509_p0 = tmp_6_reg_1229;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_509_p0 = RE_vec_128_b_reg_1140;
    end else begin
        grp_fu_509_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_509_p1 = tmp_5_reg_1223;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_509_p1 = RE_vec_128_a_reg_1134;
    end else begin
        grp_fu_509_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_513_p0 = tmp_10_reg_1241;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_513_p0 = Real_3_load_reg_1157;
    end else begin
        grp_fu_513_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_513_p1 = tmp_9_reg_1235;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_513_p1 = Real_1_load_reg_1145;
    end else begin
        grp_fu_513_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_517_p0 = tmp_16_1_reg_1253;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_517_p0 = IM_vec_128_b_reg_1173;
    end else begin
        grp_fu_517_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_517_p1 = tmp_12_1_reg_1247;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_517_p1 = IM_vec_128_a_reg_1167;
    end else begin
        grp_fu_517_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_521_p0 = tmp_23_1_fu_773_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_521_p0 = Imag_3_load_reg_1162;
    end else begin
        grp_fu_521_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_521_p1 = tmp_20_1_reg_1259;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_521_p1 = Imag_1_load_reg_1151;
    end else begin
        grp_fu_521_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_525_p0 = tmp_17_2_fu_777_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_525_p0 = RE_vec_128_a_reg_1134;
    end else begin
        grp_fu_525_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_525_p1 = tmp_5_reg_1223;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_525_p1 = tmp_11_1_fu_721_p1;
    end else begin
        grp_fu_525_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_529_p0 = tmp_23_2_fu_781_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_529_p0 = Imag_1_load_reg_1151;
    end else begin
        grp_fu_529_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_529_p1 = tmp_9_reg_1235;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_529_p1 = tmp_15_1_fu_725_p1;
    end else begin
        grp_fu_529_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_533_p0 = tmp_17_3_fu_785_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_533_p0 = IM_vec_128_a_reg_1167;
    end else begin
        grp_fu_533_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_533_p1 = tmp_12_1_reg_1247;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_533_p1 = tmp_19_1_fu_729_p1;
    end else begin
        grp_fu_533_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_537_p0 = tmp_22_1_reg_1265;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_537_p0 = Real_1_load_reg_1145;
    end else begin
        grp_fu_537_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_537_p1 = tmp_20_1_reg_1259;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_537_p1 = tmp_21_1_fu_733_p1;
    end else begin
        grp_fu_537_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        lut_reorder_I_1024_ce0 = 1'b1;
    end else begin
        lut_reorder_I_1024_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        lut_reorder_I_16384_ce0 = 1'b1;
    end else begin
        lut_reorder_I_16384_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        lut_reorder_I_4096_ce0 = 1'b1;
    end else begin
        lut_reorder_I_4096_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        lut_reorder_J_1024_ce0 = 1'b1;
    end else begin
        lut_reorder_J_1024_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        lut_reorder_J_16384_ce0 = 1'b1;
    end else begin
        lut_reorder_J_16384_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        lut_reorder_J_4096_ce0 = 1'b1;
    end else begin
        lut_reorder_J_4096_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_22_fu_648_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_22_fu_648_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter8 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter8 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (exitcond_fu_831_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (exitcond_fu_831_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((~((1'b0 == ap_block_pp1_stage1_subdone) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else if (((1'b0 == ap_block_pp1_stage1_subdone) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((1'b0 == ap_block_pp1_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp1_stage3 : begin
            if ((1'b0 == ap_block_pp1_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp1_stage3 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp1_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp1_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign arrayNo1_fu_977_p1 = tmp_24_reg_1434;

assign arrayNo_fu_1013_p1 = tmp_23_reg_1484;

assign c_1_fu_715_p2 = (c_reg_486 + 32'd4);

assign exitcond_fu_831_p2 = ((ap_phi_mux_i_phi_fu_502_p4 == tmp_14_reg_1363) ? 1'b1 : 1'b0);

assign i_1_fu_836_p2 = (ap_phi_mux_i_phi_fu_502_p4 + 13'd1);

assign indexI_1_cast_fu_921_p1 = indexI_1_reg_1419;

assign indexI_2_cast_fu_924_p1 = indexI_2_reg_1424;

assign indexI_3_fu_944_p3 = ((sel_tmp7_reg_1374[0:0] === 1'b1) ? indexI_4_cast_fu_927_p1 : indexI_6_fu_937_p3);

assign indexI_4_cast_fu_927_p1 = indexI_4_reg_1429;

assign indexI_5_fu_930_p3 = ((tmp_reg_1058[0:0] === 1'b1) ? indexI_1_cast_fu_921_p1 : indexI_fu_118);

assign indexI_6_fu_937_p3 = ((sel_tmp2_reg_1368[0:0] === 1'b1) ? indexI_2_cast_fu_924_p1 : indexI_5_fu_930_p3);

assign indexJ_1_cast_fu_855_p1 = lut_reorder_J_1024_q0;

assign indexJ_2_cast_fu_859_p1 = lut_reorder_J_4096_q0;

assign indexJ_3_fu_881_p3 = ((sel_tmp7_reg_1374[0:0] === 1'b1) ? indexJ_4_cast_fu_863_p1 : indexJ_6_fu_874_p3);

assign indexJ_4_cast_fu_863_p1 = lut_reorder_J_16384_q0;

assign indexJ_5_fu_867_p3 = ((tmp_reg_1058[0:0] === 1'b1) ? indexJ_1_cast_fu_855_p1 : indexJ_fu_114);

assign indexJ_6_fu_874_p3 = ((sel_tmp2_reg_1368[0:0] === 1'b1) ? indexJ_2_cast_fu_859_p1 : indexJ_5_fu_867_p3);

assign leng_reorder_2_fu_581_p3 = ((tmp_4_fu_575_p2[0:0] === 1'b1) ? p_cast_fu_567_p3 : 12'd3968);

assign lut_reorder_I_1024_address0 = tmp_s_fu_842_p1;

assign lut_reorder_I_16384_address0 = tmp_s_fu_842_p1;

assign lut_reorder_I_4096_address0 = tmp_s_fu_842_p1;

assign lut_reorder_J_1024_address0 = tmp_s_fu_842_p1;

assign lut_reorder_J_16384_address0 = tmp_s_fu_842_p1;

assign lut_reorder_J_4096_address0 = tmp_s_fu_842_p1;

assign newIndex1_fu_663_p1 = $unsigned(newIndex_fu_653_p4);

assign newIndex2_fu_792_p1 = $unsigned(tmp_13_fu_789_p1);

assign newIndex3_fu_955_p4 = {{indexI_3_fu_944_p3[31:2]}};

assign newIndex4_fu_965_p1 = newIndex3_fu_955_p4;

assign newIndex6_fu_907_p1 = newIndex5_reg_1439;

assign newIndex_fu_653_p4 = {{ap_phi_mux_c_phi_fu_490_p4[31:2]}};

assign num_word_op_op_fu_596_p2 = (num_word + 32'd3);

assign p_cast_fu_567_p3 = ((tmp_fu_557_p2[0:0] === 1'b1) ? 12'd480 : 12'd2016);

assign p_neg_fu_541_p2 = ($signed(32'd4294967293) - $signed(num_word));

assign p_neg_t_fu_609_p2 = (30'd0 - p_lshr_reg_1053);

assign sel_tmp1_fu_810_p2 = (tmp_reg_1058 ^ 1'd1);

assign sel_tmp2_fu_815_p2 = (tmp_1_reg_1065 & sel_tmp1_fu_810_p2);

assign sel_tmp6_fu_820_p2 = (tmp_4_reg_1070 ^ 1'd1);

assign sel_tmp7_fu_825_p2 = (tmp_8_fu_802_p2 & sel_tmp6_fu_820_p2);

assign tmp_11_1_fu_721_p1 = tmp_11_1_neg_reg_1178;

assign tmp_11_1_neg_fu_679_p2 = (tmp_11_1_to_int_fu_675_p1 ^ 32'd2147483648);

assign tmp_11_1_to_int_fu_675_p1 = Real_2_q0;

assign tmp_12_fu_601_p3 = num_word_op_op_fu_596_p2[32'd31];

assign tmp_13_fu_789_p1 = newIndex_reg_1089_pp0_iter9_reg;

assign tmp_14_fu_807_p1 = $signed(leng_reorder_2_reg_1075);

assign tmp_15_1_fu_725_p1 = tmp_15_1_neg_reg_1183;

assign tmp_15_1_neg_fu_689_p2 = (tmp_15_1_to_int_fu_685_p1 ^ 32'd2147483648);

assign tmp_15_1_to_int_fu_685_p1 = Imag_3_q0;

assign tmp_17_2_fu_777_p1 = tmp_17_2_neg_reg_1276;

assign tmp_17_2_neg_fu_749_p2 = (tmp_17_2_to_int_fu_746_p1 ^ 32'd2147483648);

assign tmp_17_2_to_int_fu_746_p1 = tmp_6_reg_1229;

assign tmp_17_3_fu_785_p1 = tmp_17_3_neg_reg_1286;

assign tmp_17_3_neg_fu_767_p2 = (tmp_17_3_to_int_fu_764_p1 ^ 32'd2147483648);

assign tmp_17_3_to_int_fu_764_p1 = tmp_16_1_reg_1253;

assign tmp_18_fu_614_p4 = {{num_word_op_op_fu_596_p2[31:2]}};

assign tmp_19_1_fu_729_p1 = tmp_19_1_neg_reg_1188;

assign tmp_19_1_neg_fu_699_p2 = (tmp_19_1_to_int_fu_695_p1 ^ 32'd2147483648);

assign tmp_19_1_to_int_fu_695_p1 = Imag_2_q0;

assign tmp_19_fu_624_p3 = ((tmp_12_fu_601_p3[0:0] === 1'b1) ? p_neg_t_fu_609_p2 : tmp_18_fu_614_p4);

assign tmp_1_fu_562_p2 = ((num_word == 32'd4096) ? 1'b1 : 1'b0);

assign tmp_20_fu_632_p3 = ((tmp_2_fu_589_p3[0:0] === 1'b1) ? 30'd0 : tmp_19_fu_624_p3);

assign tmp_21_1_fu_733_p1 = tmp_21_1_neg_reg_1193;

assign tmp_21_1_neg_fu_709_p2 = (tmp_21_1_to_int_fu_705_p1 ^ 32'd2147483648);

assign tmp_21_1_to_int_fu_705_p1 = Real_3_q0;

assign tmp_21_fu_640_p3 = {{tmp_20_fu_632_p3}, {2'd0}};

assign tmp_22_fu_648_p2 = ((ap_phi_mux_c_phi_fu_490_p4 == tmp_21_reg_1080) ? 1'b1 : 1'b0);

assign tmp_23_1_fu_773_p1 = tmp_23_1_neg_reg_1271;

assign tmp_23_1_neg_fu_740_p2 = (tmp_23_1_to_int_fu_737_p1 ^ 32'd2147483648);

assign tmp_23_1_to_int_fu_737_p1 = tmp_22_1_reg_1265;

assign tmp_23_2_fu_781_p1 = tmp_23_2_neg_reg_1281;

assign tmp_23_2_neg_fu_758_p2 = (tmp_23_2_to_int_fu_755_p1 ^ 32'd2147483648);

assign tmp_23_2_to_int_fu_755_p1 = tmp_10_reg_1241;

assign tmp_23_fu_951_p1 = indexI_3_fu_944_p3[1:0];

assign tmp_24_fu_888_p1 = indexJ_3_fu_881_p3[1:0];

assign tmp_2_fu_589_p3 = num_word[32'd31];

assign tmp_4_fu_575_p2 = (tmp_fu_557_p2 | tmp_1_fu_562_p2);

assign tmp_8_fu_802_p2 = ((num_word == 32'd16384) ? 1'b1 : 1'b0);

assign tmp_fu_557_p2 = ((num_word == 32'd1024) ? 1'b1 : 1'b0);

assign tmp_s_fu_842_p1 = ap_phi_mux_i_phi_fu_502_p4;

always @ (posedge ap_clk) begin
    leng_reorder_2_reg_1075[4:0] <= 5'b00000;
    leng_reorder_2_reg_1075[8:7] <= 2'b11;
    tmp_21_reg_1080[1:0] <= 2'b00;
    tmp_14_reg_1363[4:0] <= 5'b00000;
    tmp_14_reg_1363[8:7] <= 2'b11;
end

endmodule //Reorder_fft
