# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/constr/ZC706_Gen2x4If128.xdc

# Block Designs: bd/FFT_Reorder_x_num/FFT_Reorder_x_num.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Reorder_x_num || ORIG_REF_NAME==FFT_Reorder_x_num} -quiet] -quiet

# IP: bd/FFT_Reorder_x_num/ip/FFT_Reorder_x_num_Reorder_fft_0_0/FFT_Reorder_x_num_Reorder_fft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Reorder_x_num_Reorder_fft_0_0 || ORIG_REF_NAME==FFT_Reorder_x_num_Reorder_fft_0_0} -quiet] -quiet

# XDC: bd/FFT_Reorder_x_num/FFT_Reorder_x_num_ooc.xdc
