# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.cache/wt} [current_project]
set_property parent.project_path {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/EMILIO/Desktop/HLS/FFR_Reorder_x_num/With_array_P/impl/ip [current_project]
update_ip_catalog
set_property ip_cache_permissions disable [current_project]
read_verilog {
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/trellis.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/widths.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/functions.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/types.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/ultrascale.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/xilinx.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/riffa.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tlp.vh}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/schedules.vh}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/trellis.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/widths.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/functions.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/types.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/ultrascale.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/xilinx.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/riffa.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tlp.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/schedules.vh}}]
read_verilog -library xil_defaultlib {
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/riffa_wrapper_zc706.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/hdl/FFT_Reorder_x_num_wrapper.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/async_fifo.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/async_fifo_fwft.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/channel.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/channel_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/channel_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/channel_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/chnl_tester.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/counter.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/cross_domain_signal.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/demux.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/engine_layer.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/ff.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/fifo.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/fifo_packer_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/fifo_packer_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/fifo_packer_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/interrupt.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/interrupt_controller.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/imports/new/mem_dual_port.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/mux.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/offset_flag_to_one_hot.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/offset_to_mask.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/one_hot_mux.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/pipeline.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/ram_1clk_1w_1r.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/ram_2clk_1w_1r.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/recv_credit_flow_ctrl.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/register.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/registers.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/reorder_queue.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/reorder_queue_input.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/reorder_queue_output.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/reset_controller.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/reset_extender.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/riffa.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rotate.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_engine_classic.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_engine_ultrascale.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_port_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_port_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_port_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_port_channel_gate.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_port_reader.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rx_port_requester_mux.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rxc_engine_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rxc_engine_classic.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rxc_engine_ultrascale.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rxr_engine_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rxr_engine_classic.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/rxr_engine_ultrascale.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/scsdpram.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/sg_list_reader_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/sg_list_reader_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/sg_list_reader_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/sg_list_requester.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/shiftreg.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/sync_fifo.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/syncff.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/imports/new/top_mem_DualPort_and_FFT.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/translation_xilinx.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_alignment_pipeline.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_data_fifo.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_data_pipeline.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_data_shift.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_engine.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_engine_classic.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_engine_selector.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_engine_ultrascale.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_hdr_fifo.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_multiplexer.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_multiplexer_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_multiplexer_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_multiplexer_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_buffer_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_buffer_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_buffer_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_channel_gate_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_channel_gate_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_channel_gate_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_monitor_128.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_monitor_32.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_monitor_64.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/tx_port_writer.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/txc_engine_classic.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/txc_engine_ultrascale.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/txr_engine_classic.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/riffa_hdl/txr_engine_ultrascale.v}
  {C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/hdl/ZC706_Gen2x4If128.v}
}
add_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/FFT_Reorder_x_num.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/ip/FFT_Reorder_x_num_Reorder_fft_0_0/constraints/Reorder_fft_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/prj/ZC706_Gen2x4If128.srcs/sources_1/bd/FFT_Reorder_x_num/FFT_Reorder_x_num_ooc.xdc}}]

read_ip -quiet {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/PCIeGen2x4If128.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/source/PCIeGen2x4If128-PCIE_X0Y0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/ip/synth/PCIeGen2x4If128_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/constr/ZC706_Gen2x4If128.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/EMILIO/Desktop/Nueva carpeta/riffa-master_6_v3_3/fpga/xilinx/zc706/ZC706_Gen2x4If128/constr/ZC706_Gen2x4If128.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ZC706_Gen2x4If128 -part xc7z045ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ZC706_Gen2x4If128.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ZC706_Gen2x4If128_utilization_synth.rpt -pb ZC706_Gen2x4If128_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
